grafana:
  enabled: true

  rbac:
    pspEnabled: false

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.dtikube.techinsights.com
  
  persistence:
    enabled: true
    size: 10Gi

global:
  rbac:
    pspEnabled: false
kube-state-metrics:
  podSecurityPolicy:
    enabled: false
prometheus-node-exporter:
  rbac:
    pspEnabled: false