grafana:
  enabled: true

  rbac:
    pspEnabled: false

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.dtikube.techinsights.com
  
  persistence:
    enabled: true
    size: 10Gi

prometheusOperator:
  admissionWebhooks:
    enabled: false 

prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi