grafana:
  enabled: true

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.dtikube.techinsights.com
  
  persistence:
    enabled: true
    size: 10Gi

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi